<a href="https://colab.research.google.com/github/Chayanonboo/code-for-articles/blob/main/Sample_Superstore_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Project : Sample Superstore Dataset

## Author : Chayanon Boonthanom

## Language : Python

**Date : 03 March 2026**

## **Install data from Kaggle**

In [3]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "SampleSuperstore.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "bravehart101/sample-supermarket-dataset",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

/tmp/ipykernel_308/4009618429.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).

## **Check head**

In [2]:
## check head
print("First 5 records:", df.head())

First 5 records:         Ship Mode    Segment        Country             City       State  \
0    Second Class   Consumer  United States        Henderson    Kentucky
1    Second Class   Consumer  United States        Henderson    Kentucky
2    Second Class  Corporate  United States      Los Angeles  California
3  Standard Class   Consumer  United States  Fort Lauderdale     Florida
4  Standard Class   Consumer  United States  Fort Lauderdale     Florida

   Postal Code Region         Category Sub-Category     Sales  Quantity  \
0        42420  South        Furniture    Bookcases  261.9600         2
1        42420  South        Furniture       Chairs  731.9400         3
2        90036   West  Office Supplies       Labels   14.6200         2
3        33311  South        Furniture       Tables  957.5775         5
4        33311  South  Office Supplies      Storage   22.3680         2

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164

In [ ]:
## Check Info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ship Mode     9994 non-null   object
 1   Segment       9994 non-null   object
 2   Country       9994 non-null   object
 3   City          9994 non-null   object
 4   State         9994 non-null   object
 5   Postal Code   9994 non-null   int64
 6   Region        9994 non-null   object
 7   Category      9994 non-null   object
 8   Sub-Category  9994 non-null   object
 9   Sales         9994 non-null   float64
 10  Quantity      9994 non-null   int64
 11  Discount      9994 non-null   float64
 12  Profit        9994 non-null   float64
dtypes: float64(3), int64(2), object(8)
memory usage: 1015.1+ KB

In [ ]:
## Check nunique Column
df.nunique()

Ship Mode          4
Segment            3
Country            1
City             531
State             49
Postal Code      631
Region             4
Category           3
Sub-Category      17
Sales           5825
Quantity          14
Discount          12
Profit          7287
dtype: int64

In [ ]:
## check NA Value
df.isnull().sum()

Ship Mode       0
Segment         0
Country         0
City            0
State           0
Postal Code     0
Region          0
Category        0
Sub-Category    0
Sales           0
Quantity        0
Discount        0
Profit          0
dtype: int64

In [ ]:
## 1. df.sales and product all product
pd.options.display.float_format = '{:,.2f}'.format
df[['Sales', 'Profit']].sum()

Sales    2,297,200.86
Profit     286,397.02
dtype: float64

In [ ]:
## df.sub-Category type
df['Sub-Category'].value_counts()

Sub-Category
Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Art             796
Accessories     775
Chairs          617
Appliances      466
Labels          364
Tables          319
Envelopes       254
Bookcases       228
Fasteners       217
Supplies        190
Machines        115
Copiers          68
Name: count, dtype: int64

In [ ]:
# ต้องแปลงเป็น DataFrame ก่อน แล้วค่อย style
counts_df = df['Sub-Category'].value_counts().to_frame()
print(counts_df)

              count
Sub-Category
Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Art             796
Accessories     775
Chairs          617
Appliances      466
Labels          364
Tables          319
Envelopes       254
Bookcases       228
Fasteners       217
Supplies        190
Machines        115
Copiers          68

In [ ]:
len(df['Sub-Category'].unique())

17

In [ ]:
## 2. Product Variety: How many total sub-categories are there, and which one has the highest number of orders?
sub_category_unique = df['Sub-Category'].unique()
print(f"Order: {sub_category_unique}\nCount: {len(sub_category_unique)}")

Order: ['Bookcases' 'Chairs' 'Labels' 'Tables' 'Storage' 'Furnishings' 'Art'
 'Phones' 'Binders' 'Appliances' 'Paper' 'Accessories' 'Envelopes'
 'Fasteners' 'Supplies' 'Machines' 'Copiers']
Count: 17

In [ ]:
## 3. What segment buy most
sales_by_segment = df.groupby('Segment')['Sales'].sum()
print(sales_by_segment.apply(lambda x: "{:,.2f}".format(x)))

Segment
Consumer       1,161,401.34
Corporate        706,146.37
Home Office      429,653.15
Name: Sales, dtype: object

In [ ]:
## 4. ship frequency
count_ship_mode = df['Ship Mode'].value_counts().to_frame()
print(count_ship_mode)

                count
Ship Mode
Standard Class   5968
Second Class     1945
First Class      1538
Same Day          543

In [ ]:
## country frequency
count_ship_region = df['Region'].value_counts().to_frame()
print(count_ship_region)

         count
Region
West      3203
East      2848
Central   2323
South     1620

In [ ]:
# สร้าง DataFrame ใหม่เพื่อสรุปข้อมูล
summary_df = pd.DataFrame({
    'Count (nunique)': df.nunique(),
    'Examples (unique)': df.apply(lambda x: x.unique()[:5]) # ดูตัวอย่างแค่ 5 ตัวแรก
})

# แสดงผล
summary_df

,Count (nunique),Examples (unique)
Ship Mode,4,"[Second Class, Standard Class, First Class, Sa..."
Segment,3,"[Consumer, Corporate, Home Office]"
Country,1,[United States]
City,531,"[Henderson, Los Angeles, Fort Lauderdale, Conc..."
State,49,"[Kentucky, California, Florida, North Carolina..."
Postal Code,631,"[42420, 90036, 33311, 90032, 28027]"
Region,4,"[South, West, Central, East]"
Category,3,"[Furniture, Office Supplies, Technology]"
Sub-Category,17,"[Bookcases, Chairs, Labels, Tables, Storage]"
Sales,5825,"[261.96, 731.94, 14.62, 957.5775, 22.368]"
Quantity,14,"[2, 3, 5, 7, 4]"
Discount,12,"[0.0, 0.45, 0.2, 0.8, 0.3]"
Profit,7287,"[41.9136, 219.582, 6.8714, -383.031, 2.5164]"

In [ ]:
## 5. sum Sales Quantity Discount Profit
type_sum = df[['Sales','Quantity','Discount',"Profit"]].sum()
region_sum = df.groupby("Region")[['Sales','Quantity','Discount',"Profit"]].sum().sort_values(by='Profit', ascending=False)
print(type_sum)
print(region_sum)

Sales      2,297,200.86
Quantity      37,873.00
Discount       1,561.09
Profit       286,397.02
dtype: float64
             Sales  Quantity  Discount     Profit
Region
West    725,457.82     12266    350.20 108,418.45
East    678,781.24     10618    414.00  91,522.78
South   391,721.91      6209    238.55  46,749.43
Central 501,239.89      8780    558.34  39,706.36

In [ ]:
## 6. Sub-Category that make company Loss the most is.
the_most_loss = df.groupby("Sub-Category")['Profit'].sum().sort_values(ascending=True)
print(the_most_loss)

Sub-Category
Tables        -17,725.48
Bookcases      -3,472.56
Supplies       -1,189.10
Fasteners         949.52
Machines        3,384.76
Labels          5,546.25
Art             6,527.79
Envelopes       6,964.18
Furnishings    13,059.14
Appliances     18,138.01
Storage        21,278.83
Chairs         26,590.17
Binders        30,221.76
Paper          34,053.57
Accessories    41,936.64
Phones         44,515.73
Copiers        55,617.82
Name: Profit, dtype: float64

In [ ]:
## 7. the most state most sale but profit less
the_most_state = df.groupby("State")[['Profit','Sales']].sum().sort_values(by='Profit', ascending=True)
print(the_most_state)

                         Profit      Sales
State
Texas                -25,729.36 170,188.05
Ohio                 -16,971.38  78,258.14
Pennsylvania         -15,559.96 116,511.91
Illinois             -12,607.89  80,166.10
North Carolina        -7,490.91  55,603.16
Colorado              -6,527.86  32,108.12
Tennessee             -5,341.69  30,661.87
Arizona               -3,427.92  35,282.00
Florida               -3,399.30  89,473.71
Oregon                -1,190.47  17,431.15
Wyoming                  100.20   1,603.14
West Virginia            185.92   1,209.82
North Dakota             230.15     919.91
South Dakota             394.83   1,315.56
Maine                    454.49   1,270.53
Idaho                    826.72   4,382.49
Kansas                   836.44   2,914.31
District of Columbia   1,059.59   2,865.02
New Mexico             1,157.12   4,783.52
Iowa                   1,183.81   4,579.76
New Hampshire          1,706.50   7,292.52
South Carolina         1,769.06   8,481.71
Montana                1,833.33   5,589.35
Nebraska               2,037.09   7,464.93
Louisiana              2,196.10   9,217.03
Vermont                2,244.98   8,929.37
Utah                   2,546.53  11,220.06
Mississippi            3,172.98  10,771.34
Nevada                 3,316.77  16,729.10
Connecticut            3,511.49  13,384.36
Arkansas               4,008.69  11,678.13
Oklahoma               4,853.96  19,683.39
Alabama                5,786.83  19,510.64
Missouri               6,436.21  22,205.15
Massachusetts          6,785.50  28,634.43
Maryland               7,031.18  23,705.52
Rhode Island           7,285.63  22,627.96
Wisconsin              8,401.80  32,114.61
New Jersey             9,772.91  35,764.31
Delaware               9,977.37  27,451.07
Minnesota             10,823.19  29,863.15
Kentucky              11,199.70  36,591.75
Georgia               16,250.04  49,095.84
Indiana               18,382.94  53,555.36
Virginia              18,597.95  70,636.72
Michigan              24,463.19  76,269.61
Washington            33,402.65 138,641.27
New York              74,038.55 310,876.27
California            76,381.39 457,687.63

In [ ]:
## 8 Discount and Profit
high_discount_df = df[df['Discount'] > 0.5]
total_profit_high_discount = high_discount_df['Profit'].sum()
print(f"Total Profit for products with Discount > 0.5: {total_profit_high_discount:,.2f}")

Total Profit for products with Discount > 0.5: -76,559.05

In [ ]:
# รูปแบบ: {'ชื่อเก่า': 'ชื่อใหม่'}
df_new = df.rename(columns={
    'Ship Mode': 'ship_mode',
    'Postal Code': 'postal_code',
    'Sub-Category': 'sub_category'
})

In [ ]:
df_new.head()

,ship_mode,Segment,Country,City,State,postal_code,Region,Category,sub_category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,Sale,2,0.00,41.91
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,Sale,3,0.00,219.58
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,Sale,2,0.00,6.87
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,Sale,5,0.45,-383.03
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,Sale,2,0.20,2.52